# Generated by Django 5.1.3 on 2024-12-03 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('Start_Date_Time', models.DateTimeField()),
                ('End_Date_Time', models.DateTimeField()),
                ('Localisation', models.CharField(blank=True, max_length=255, null=True)),
                ('Participation_Link', models.URLField(blank=True, max_length=255, null=True)),
                ('Reminber_Set', models.CharField(blank=True, max_length=255, null=True)),
                ('Summary', models.CharField(blank=True, max_length=255, null=True)),
                ('Timezone', models.CharField(max_length=25)),
                ('Recurrence', models.CharField(choices=[('every week', 'Every Week'), ('every monday', 'Every Monday')], default='every week', max_length=100, null=True)),
                ('Attendees', models.TextField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Organized_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
