# Generated by Django 5.1.3 on 2025-04-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenements', '0002_alter_events_organized_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='Organized_By',
        ),
    ]
