# Generated by Django 5.1.3 on 2025-04-03 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentorship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentoring',
            name='Mentee_Id',
        ),
        migrations.RemoveField(
            model_name='mentoring',
            name='Mentor_Id',
        ),
    ]
