# Generated by Django 5.1.3 on 2024-12-02 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('Content_Link', models.URLField(max_length=255)),
                ('Duration', models.CharField(max_length=50)),
                ('Status', models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('drafted', 'Drafted')], default='drafted', max_length=50)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Update_At', models.DateTimeField(auto_now=True)),
                ('Created_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Formation_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content_Type', models.CharField(choices=[('video', 'Video'), ('quiz', 'Quiz'), ('document', 'Document')], max_length=50)),
                ('Content_Link', models.URLField(max_length=100)),
                ('Description', models.TextField()),
                ('Duration', models.CharField(max_length=50)),
                ('Order', models.PositiveIntegerField()),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Updated_At', models.DateTimeField(auto_now=True)),
                ('Formation_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formation.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Ressources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Type', models.CharField(choices=[('audio', 'Audio'), ('document', 'Document'), ('video', 'Video')], max_length=50)),
                ('File_Link', models.URLField(max_length=255)),
                ('Published_Date', models.DateField()),
                ('Status', models.CharField(choices=[('drafted', 'Drafted'), ('published', 'Published')], default='drafted', max_length=50)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
                ('Update_At', models.DateTimeField(auto_now=True)),
                ('Author_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.customuser')),
            ],
        ),
    ]
