# Generated by Django 5.1.3 on 2025-03-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressources',
            name='Author_Id',
        ),
    ]
