# Generated by Django 5.1.3 on 2025-04-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formation', '0002_remove_ressources_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='Created_By',
        ),
    ]
