# Generated by Django 5.1.2 on 2025-02-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_patient', models.CharField(blank=True, max_length=25)),
                ('nom', models.CharField(max_length=25)),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')])),
                ('age', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Frottis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='')),
                ('id_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doameki.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Rapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_fichier', models.FileField(upload_to='')),
                ('id_frottis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doameki.frottis')),
            ],
        ),
    ]
