# Generated by Django 5.1.2 on 2025-03-01 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doameki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frottis',
            name='status',
            field=models.CharField(max_length=25),
        ),
    ]
