# Generated by Django 5.1.2 on 2025-04-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doameki', '0003_alter_frottis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frottis',
            name='status',
            field=models.CharField(max_length=150),
        ),
    ]
